insert into questions (text, theme, source) values
  ('What made you both laugh the hardest this week?', 'funny', 'manual'),
  ('What''s something funny one of you said or did that I''ll want to remember?', 'funny', 'manual'),
  ('What new word or skill did one of you pick up this week?', 'milestone', 'manual'),
  ('What milestone happened this week, big or small?', 'milestone', 'manual'),
  ('What was your favorite moment with both of you together this week?', 'feelings', 'manual'),
  ('What do I love most about each of you right now, specifically?', 'feelings', 'manual'),
  ('What was the hardest part of parenting this week, and how did it go?', 'feelings', 'manual'),
  ('What''s something I never want to forget about this stage of your lives?', 'feelings', 'manual'),
  ('What''s your current daily routine look like — what do you both love about it?', 'routines', 'manual'),
  ('What''s a small ritual or habit we have right now that I hope you''ll remember?', 'routines', 'manual'),
  ('What did we eat, watch, or do together that felt like a real family moment?', 'routines', 'manual'),
  ('What am I grateful for about being your parent this week?', 'gratitude', 'manual'),
  ('What did you both teach me this week without meaning to?', 'gratitude', 'manual'),
  ('If I could freeze one moment from this week to show you someday, what would it be?', 'gratitude', 'manual'),
  ('What are you both obsessed with right now?', 'routines', 'manual'),
  ('What''s one thing I did this week that I''m proud of as your parent?', 'feelings', 'manual'),
  ('What''s one thing I wish I''d done differently this week?', 'feelings', 'manual'),
  ('What are you both afraid of right now, and how do we help you through it?', 'feelings', 'manual'),
  ('What game, book, or song is on repeat in our house right now?', 'routines', 'manual'),
  ('What''s something one of you did this week that surprised me?', 'milestone', 'manual');
